resources: []

jobs:
- name: semgrep-scan
  plan:
  - task: semgrep-scan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: returntocorp/semgrep}
      params:
        SEMGREP_APP_TOKEN: ((semgrep_cli_token))  # Pass the Semgrep CLI token as an environment variable
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          echo "Logging into Semgrep"
          echo $SEMGREP_APP_TOKEN | semgrep login  # Pipe the token into semgrep login
          
          echo "Cloning repository"
          git clone https://github.com/kmenon95/WebGoat.NET.git

          echo "Changing directory to cloned repository"
          cd WebGoat.NET

          if [[ -n "$CI_PULL_REQUEST" ]]; then
            # If it's a PR branch, checkout the PR branch and run Semgrep
            echo "Running Semgrep scan on pull request branch"
            git fetch origin pull/$CI_PULL_REQUEST/head:pr-$CI_PULL_REQUEST
            git checkout pr-$CI_PULL_REQUEST
          else
            # Otherwise, just run Semgrep on the main branch
            echo "Running Semgrep scan on main branch"
            git checkout main
          fi

          echo "Running Semgrep scan"
          semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'
