resources:
- name: hello-world-repo
  type: git
  source:
    uri: https://github.com/your-username/hello-world.git
    branch: main

jobs:
- name: say-hello
  plan:
  - get: hello-world-repo
    trigger: true
  - task: hello-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      run:
        path: echo
        args: ["Hello, world!"]
