resources: []

jobs:
- name: semgrep-scan
  plan:
  - task: semgrep-scan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: returntocorp/semgrep}
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          semgrep ci .
