resources: []

jobs:
- name: semgrep-scan
  plan:
  - task: semgrep-scan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: returntocorp/semgrep}
      params:
        SEMGREP_APP_TOKEN: ((semgrep_cli_token))  # Pass the Semgrep CLI token as an environment variable
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          echo "Logging into Semgrep"
          echo $SEMGREP_APP_TOKEN | semgrep login  # Pipe the token into semgrep login
          
          echo "Cloning repository"
          git clone https://github.com/kmenon95/WebGoat.NET.git

          echo "Changing directory to cloned repository"
          cd WebGoat.NET

          # Fetch all branches
          git fetch --all
          
          # Iterate over all branches
          for branch in $(git branch -r | grep -v '->'); do
            # Trim whitespace
            branch=$(echo $branch | tr -d '[:space:]')
            # Check if it's a pull request branch
            if [[ $branch =~ ^origin/pr-[0-9]+$ ]]; then
              echo "Running Semgrep scan on pull request branch: $branch"
              # Fetch the pull request branch and checkout
              git fetch origin $branch:refs/remotes/$branch
              git checkout $branch
            else
              # Otherwise, it's a regular branch
              echo "Running Semgrep scan on branch: $branch"
              # Checkout the branch
              git checkout ${branch#*/}
            fi

            # Run Semgrep scan
            echo "Running Semgrep scan"
            semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'
          done
