resources: []

jobs:
- name: semgrep-scan
  plan:
  - task: semgrep-scan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: returntocorp/semgrep}
      params:
        SEMGREP_APP_TOKEN: ((semgrep_cli_token))  # Pass the Semgrep CLI token as an environment variable
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          echo "Logging into Semgrep"
          echo $SEMGREP_APP_TOKEN | semgrep login  # Pipe the token into semgrep login
          
          echo "Cloning repository"
          git clone https://github.com/kmenon95/WebGoat.NET.git

          echo "Changing directory to cloned repository"
          cd WebGoat.NET

          # Fetch all branches
          git fetch --all
          
          # Get the name of the default branch
          default_branch=$(git remote show origin | grep 'HEAD branch' | awk '{print $NF}')

          # Fetch pull request information using GitHub API
          pull_requests=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/kmenon95/WebGoat.NET/pulls")

          # Run Semgrep scan on default branch
          echo "Running Semgrep scan on default branch: $default_branch"
          git checkout $default_branch
          echo "Running Semgrep scan"
          semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'

          # Run Semgrep scan on open pull requests
          for pr_number in $(echo "$pull_requests" | jq -r '.[].number'); do
            echo "Running Semgrep scan on pull request #$pr_number"
            git fetch origin refs/pull/$pr_number/head:pr-$pr_number
            git checkout pr-$pr_number
            echo "Running Semgrep scan"
            semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'
          done
