resources: []

jobs:
- name: semgrep-scan
  plan:
  - task: semgrep-scan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: returntocorp/semgrep}
      params:
        SEMGREP_APP_TOKEN: ((semgrep_cli_token))  # Pass the Semgrep CLI token as an environment variable
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          echo "Logging into Semgrep"
          echo $SEMGREP_APP_TOKEN | semgrep login  # Pipe the token into semgrep login
          
          echo "Cloning repository"
          git clone https://github.com/kmenon95/WebGoat.NET.git

          echo "Changing directory to cloned repository"
          cd WebGoat.NET

          # Fetch all branches
          git fetch --all
          
          # Get the name of the default branch
          default_branch=$(git remote show origin | grep 'HEAD branch' | awk '{print $NF}')
          
          # Get the list of branches using git ls-remote
          branches=$(git ls-remote --heads origin)
          
          # Iterate over all branches
          for branch_info in $branches; do
            # Extract branch name
            branch=$(echo $branch_info | cut -d'/' -f3)
            # Check if it's the default branch
            if [[ $branch = "$default_branch" ]]; then
              echo "Running Semgrep scan on default branch: $default_branch"
              # Fetch and checkout the default branch
              git checkout $default_branch
            else
              # Check if it's a pull request branch
              if [[ $branch =~ ^pr-[0-9]+$ ]]; then
                echo "Running Semgrep scan on pull request branch: $branch"
                # Fetch the pull request branch and checkout
                git fetch origin $branch:$branch
                git checkout $branch
              else
                # Skip regular branches
                continue
              fi
            fi

            # Run Semgrep scan
            echo "Running Semgrep scan"
            semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'
          done
