resources: []

jobs:
- name: semgrep-scan
  plan:
  - task: semgrep-scan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: returntocorp/semgrep}
      params:
        SEMGREP_APP_TOKEN: ((semgrep_cli_token))  # Pass the Semgrep CLI token as an environment variable
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          echo "Logging into Semgrep"
          echo $SEMGREP_APP_TOKEN | semgrep login  # Pipe the token into semgrep login
          
          echo "Cloning repository"
          git clone https://github.com/kmenon95/WebGoat.NET.git

          echo "Changing directory to cloned repository"
          cd WebGoat.NET

          # Fetch all branches
          git fetch --all
          
          # Get the name of the default branch
          default_branch=$(git remote show origin | grep 'HEAD branch' | awk '{print $NF}')
          
          # Iterate over all branches
          for branch in $(git branch -r | grep -v '->'); do
            # Extract branch name
            branch_name=$(echo $branch | sed 's/origin\///')
            
            # Check if it's a pull request branch
            if [[ "$branch_name" =~ ^origin/pr-[0-9]+$ ]]; then
              echo "Running Semgrep scan on pull request branch: $branch_name"
              # Fetch the pull request branch and checkout
              git fetch origin $branch_name:$branch_name
              git checkout $branch_name

              # Run Semgrep scan
              echo "Running Semgrep scan"
              semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'
            fi
          done
          
          # Checkout the default branch and run Semgrep scan if no pull request branches were found
          git checkout $default_branch
          echo "Running Semgrep scan on default branch: $default_branch"
          semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'
