resources: []

jobs:
- name: semgrep-scan
  plan:
  - task: semgrep-scan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: returntocorp/semgrep}
      params:
        SEMGREP_APP_TOKEN: ((semgrep_cli_token))  # Pass the Semgrep CLI token as an environment variable
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          echo "Logging into Semgrep"
          echo $SEMGREP_APP_TOKEN | semgrep login  # Pipe the token into semgrep login
          
          echo "Cloning repository"
          git clone https://github.com/kmenon95/WebGoat.NET.git

          echo "Changing directory to cloned repository"
          cd WebGoat.NET

          # Fetch all branches
          git fetch --all
          
          # Get the name of the default branch
          default_branch=$(git remote show origin | grep 'HEAD branch' | awk '{print $NF}')

          # Fetch pull request information using GitHub API
          pull_requests=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/kmenon95/WebGoat.NET/pulls")

          # Iterate over all branches
          for branch_info in $(git branch -r | grep -v '->'); do
            # Extract branch name
            branch=$(echo $branch_info | tr -d '[:space:]')
            # Check if it's the default branch
            if [[ $branch = "origin/$default_branch" ]]; then
              echo "Running Semgrep scan on default branch: $default_branch"
              # Fetch and checkout the default branch
              git checkout $default_branch
            else
              # Check if it's a pull request branch
              if [[ $branch =~ ^origin/pr-[0-9]+$ ]]; then
                # Extract PR number from branch name
                pr_number=$(echo $branch | cut -d'-' -f2)
                # Check if PR is open
                if echo "$pull_requests" | jq ".[] | select(.number == $pr_number) | .state" | grep -q "open"; then
                  echo "Running Semgrep scan on pull request branch: $branch"
                  # Fetch the pull request branch and checkout
                  git fetch origin $branch:$branch
                  git checkout $branch
                  # Run Semgrep scan
                  echo "Running Semgrep scan"
                  semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'
                fi
              else
                # Otherwise, it's a regular branch
                echo "Skipping Semgrep scan on branch: $branch"
              fi
            fi
          done
