resources: []

jobs:
- name: semgrep-scan
  plan:
  - task: fetch-repo
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: alpine/git, tag: latest }
      params:
        REPO_URL: https://github.com/kmenon95/concourse-ci/archive/refs/heads/main.zip
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          apk add --no-cache curl
          curl -L -o repo.zip $REPO_URL
          unzip repo.zip
          rm repo.zip
  - task: semgrep-scan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: returntocorp/semgrep}
      params:
        SEMGREP_APP_TOKEN: ((semgrep_cli_token))  # Pass the Semgrep CLI token as an environment variable
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          echo "Logging into Semgrep"
          echo $SEMGREP_APP_TOKEN | semgrep login  # Pipe the token into semgrep login
          semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'
