resources: []

jobs:
- name: semgrep-scan
  plan:
  - task: semgrep-scan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: returntocorp/semgrep}
      params:
        SEMGREP_APP_TOKEN: ((semgrep_cli_token))  # Pass the Semgrep CLI token as an environment variable
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          echo "Logging into Semgrep"
          echo $SEMGREP_APP_TOKEN | semgrep login  # Pipe the token into semgrep login
          
          echo "Cloning repository"
          git clone https://github.com/kmenon95/WebGoat.NET.git

          echo "Changing directory to cloned repository"
          cd WebGoat.NET

          # Fetch all pull request branches
          pull_requests=$(curl -s https://api.github.com/repos/kmenon95/WebGoat.NET/pulls)
          
          # Check if there are any open pull requests
          if [[ $(echo $pull_requests | jq length) -eq 0 ]]; then
              echo "No open pull requests found. Exiting."
              exit 0
          fi

          # Iterate over all pull requests
          for pr_info in $(echo $pull_requests | jq -r '.[] | @base64'); do
              # Extract branch name
              branch=$(echo $pr_info | base64 -d | jq -r '.head.ref')
              
              # Checkout the pull request branch
              echo "Running Semgrep scan on pull request branch: $branch"
              git fetch origin $branch:$branch
              git checkout $branch

              # Run Semgrep scan
              echo "Running Semgrep scan"
              semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'
          done
