resources:
- name: semgrep
  type: github-release
  source:
    owner: kmenon95
    repository: concourse-ci
    release: latest

jobs:
- name: semgrep
  plan:
  - get: semgrep
    trigger: true
    version: { branch: main }
  - task: semgrep-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: returntocorp/semgrep}
      inputs:
      - name: semgrep
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          cd semgrep
          semgrep ci --exclude='*.webp' --exclude='*.png' --exclude='*.svg' --exclude='*.woff' --exclude='*.woff2' --exclude='*.jpg' --exclude='*.glb' --exclude='*.pdf' --exclude='*.lock' --exclude='*.md'  --exclude='*.pro' --exclude='.github/*'
